### ISSUE TITLE
under which License is the QtCEF released?

### ISSUE THREAD

**Issue by rahmanih** [Dax89/QtCEF#1]
Hi,
Could you please add a "COPYING" file  preferably BSD :)

regards
Haithem.

**Comment by Dax89** [comment]
Hi,

Done :)
As I writed in the repo's ReadMe, this is testing code, not ready for create real applications

**Comment by rahmanih** [comment]
thanks!

**Comment by toby20130333** [comment]
@Dax89 Hi
I want to use this code but i modified some code and build on cef3.2526 version and get some errors
You do not maintain this project?many people want to use cef3 as a The browser to embed into Qt app

**Comment by Dax89** [comment]
Hi @toby20130333 :)

I've realized that there is too much work to do for a single person, that's why there is very low activity in this repo.
The idea was to create two components (QWidgets and QQuickItem) in order to use it with Qt5 with similar APIs like the QtWebKit and QtWebEngine ones.

I've never tested this binding with recent CEF versions, I will look at that in order to make it compilable again.

**Comment by toby20130333** [comment]
@Dax89 thank you hope to do well done for qt cef
